version: '3'
services: 
  react:
    build: ./client/
    ports: 
      - "3000:3000"
    depends_on: 
      - server
  server:
    image: abdallahyossf/springboot:test
    ports: 
      - "8080:8080" 